INSERT INTO modelos (descripcion)
           values("serger")
INSERT INTO modelos (descripcion)
           values("doble punta")      
INSERT INTO modelos (descripcion)
           values("Brother")                 
           
    INSERT INTO tipo_telas(descripcion)
                    values("algodon")
                    
   INSERT INTO tipo_telas(descripcion)
                   values("cuero")  
    INSERT INTO tipo_telas(descripcion)                
                    values("lino")  
   INSERT INTO MaquinaDeCoser(modelo,velocidad_actual,velocidad_maxima,tipo_puntada,tipo_tela )
                      values( 1,10,700,"cadeneta",1)
   INSERT INTO MaquinaDeCoser(modelo,velocidad_actual,velocidad_maxima,tipo_puntada,tipo_tela )
                      values( 2,20,800,"zigzag",2)  
   INSERT INTO MaquinaDeCoser(modelo,velocidad_actual,velocidad_maxima,tipo_puntada,tipo_tela )
                      values( 3,15,750,"overlock",3)                   